use crate::cmd::error::{DbError, DbErrorKind};
use crate::cmd::object::Object;
use crate::cmd::os;
use crate::hex;
use rand::RngExt;
use rand::distr::Alphanumeric;
use sha1::{Digest, Sha1};
use std::collections::HashMap;
use std::fs;
use std::io::{self, ErrorKind};
use std::path::PathBuf;

pub(super) struct Database {
    pub(super) path: PathBuf,
}

// toDo: info and packs files
impl Database {
    pub(super) fn store(&self, object: Object) -> Result<[u8; 20], DbError> {
        let obj_type = object.obj_type().as_bytes();
        let content = object.serialize();
        // The header for each object is: object type, a space, the size of the object(result of
        // serialization) and a nul byte. These are the bytes that will be used for compression
        let mut bytes = Vec::new();
        bytes.extend_from_slice(obj_type);
        bytes.push(b' ');
        bytes.extend_from_slice(content.len().to_string().as_bytes());
        bytes.push(0);
        // The final representation is header + content
        bytes.extend(content);
        let hash: [u8; 20] = Sha1::digest(&bytes).into();
        // the hash is bytes generated by Sha1
        // we need to map those bytes to their hex representation, decimal -> hex
        // don't confused it with utf-8
        // map [144, 58, 113, 173, 48, 13, 90, 161, 186, 12, ...] to [90, 3a, 71, ad, 30, 0d, 5a...].
        // Any u8 can be represented with at most 2 hex digits so the output is a String of length 40.
        // u8 spans from 0 to 255 which is equivalent to 0x00 - 0xFF
        // both the 20 raw bytes and the 40-character hex string are the same hash. They are two
        // representations of the same 160-bit value
        let hex = hex::bytes_as_hex(&hash);
        // the first 2 characters are the name of the folder in /objects, the rest are the name
        // of the file .lit/objects/90/3a71ad300d...
        // the two character split is just to avoid having of thousands of files in one directory,
        // which would slow down file systems
        let parent = self.path.join(&hex[..2]);
        // if the parent dir does not exist, create parent first .lit/objects/90/ before trying to
        // write tmp
        match fs::create_dir(&parent) {
            Ok(_) => {}
            Err(err) if err.kind() == ErrorKind::AlreadyExists => {
                if !parent.is_dir() {
                    let err = io::Error::new(
                        ErrorKind::AlreadyExists,
                        "object directory path exists but is not a directory",
                    );
                    return Err(DbError {
                        path: parent,
                        kind: DbErrorKind::Io { source: err },
                    });
                }
            }
            Err(err) => {
                return Err(DbError {
                    path: parent,
                    kind: DbErrorKind::Io { source: err },
                });
            }
        }

        // If the hash already exists in .lit/objects/, the content is guaranteed to be identical
        // (same content -> same hash), so writing it again is pointless.
        let path = parent.join(&hex[2..]);
        if path.exists() {
            return Ok(hash);
        }
        let tmp_path = parent.join(gen_tmp_name());
        // this will create only the temp file and not any of the parent dir if missing
        // .lit/objects/90/tmp_obj_gNLJvt
        // TODO: maybe we use zlib?
        let compressed = deflate::deflate_bytes(&bytes);
        fs::write(&tmp_path, compressed).map_err(|err| DbError {
            path: parent.to_path_buf(),
            kind: DbErrorKind::Io { source: err },
        })?;

        // we return the rename error even if remove_file() fails because that was the main reason
        if let Err(err) = fs::rename(&tmp_path, &path) {
            // Try to clean up the temp file before returning the error
            let _ = fs::remove_file(&tmp_path);
            return Err(DbError {
                path: tmp_path,
                kind: DbErrorKind::Io { source: err },
            });
        }
        Ok(hash)
    }

    pub(super) fn load(&self, oid: &str) -> Result<Option<Object>, DbError> {
        if oid.len() != 40 {
            return Ok(None);
        }
        let path = self.path.join(&oid[..2]).join(&oid[2..]);
        let content = match fs::read(&path) {
            Ok(content) => content,
            Err(err) if matches!(err.kind(), ErrorKind::NotFound | ErrorKind::IsADirectory) => {
                return Ok(None);
            }
            Err(err) => {
                return Err(DbError {
                    path,
                    kind: DbErrorKind::Io { source: err },
                });
            }
        };

        let bytes = match inflate::inflate_bytes(&content) {
            Ok(bytes) => bytes,
            Err(err) => {
                return Err(DbError {
                    path,
                    kind: DbErrorKind::Decompress { reason: err },
                });
            }
        };

        let hash: [u8; 20] = Sha1::digest(&bytes).into();
        let hex = hex::bytes_as_hex(&hash);
        if hex != oid {
            // tampered object: someone opened the file, changed its contents, compressed the new
            // content and wrote back to the file, the hashes do not match
            return Err(DbError {
                path,
                kind: DbErrorKind::HashMismatch {
                    oid: oid.to_owned(),
                },
            });
        }
        // the information from any parsing error that occurs during loading an object is never returned
        // to the user. It means something is wrong with our on-disk format. Bad object with {oid}
        // is all they are going to see. The information is only needed for debugging.
        Ok(Some(Object::deserialize(&bytes).map_err(|_| DbError {
            path,
            kind: DbErrorKind::BadObject {
                oid: oid.to_owned(),
            },
        })?))
    }

    pub(super) fn load_tree_files(&self, tree_oid: &str) -> Result<HashMap<Vec<u8>, ([u8; 20], u32)>, DbError> {
        let mut files = HashMap::new();
        self.collect_tree_files(&mut files, b"", tree_oid)?;

        Ok(files)
    }

    fn collect_tree_files(
        &self,
        files: &mut HashMap<Vec<u8>, ([u8; 20], u32)>,
        prefix: &[u8],
        tree_oid: &str,
    ) -> Result<(), DbError> {
        let entries = match self.load(tree_oid)? {
            Some(Object::Tree(entries)) => entries,
            Some(object) => return Err(DbError {
                path: os::bytes_to_path(prefix),
                kind: DbErrorKind::ObjectTypeMisMatch {
                    // to_string() calls String::from() and String::from() calls to_owned(). There is
                    // no performance cost in any of them
                    expected: "tree".to_owned(),
                    found: object.obj_type().to_owned(),
                    oid: tree_oid.to_owned(),
                }
            }),
            None => return Err(DbError {
                path: os::bytes_to_path(prefix),
                kind: DbErrorKind::NotFound { oid: tree_oid.to_owned() }
            }),
        };

        for entry in entries {
            if entry.mode == os::DIR {
                let path = extend_path(prefix, &entry.name);
                // dfs
                self.collect_tree_files(files, &path, &hex::bytes_as_hex(&entry.oid))?;
            } else {
                files.insert(prefix.to_vec(), (entry.oid, entry.mode));
            }
        }
        Ok(())
    }
}

pub(super) fn hash(obj_type: &[u8], content: &[u8]) -> [u8; 20] {
    // The header for each object is: object type, a space, the length of the object(result of
    // serialization) and a nul byte
    let mut bytes = Vec::new();
    bytes.extend_from_slice(obj_type);
    bytes.push(b' ');
    bytes.extend_from_slice(content.len().to_string().as_bytes());
    bytes.push(0);
    // The final representation is header + content
    bytes.extend(content);
    Sha1::digest(bytes).into()
}

// there is an edge case of a collision where 2 different processes could in theory generate the same
// tmp file name, and they will overwrite each others content, we have a case of competing writes, rare
// but can happen, could use Lockfile, but it is highly unlikely
fn gen_tmp_name() -> String {
    let suffix: String = (0..6)
        .map(|_| rand::rng().sample(Alphanumeric) as char)
        .collect();
    format!("tmp_obj_{suffix}")
}

// this method is used to builds the path when walking a tree starting from the root. if we walk
// src and has 1 file: main.rs then the path stored on the map is src/main.rs it is the location of
// the file build incrementally one level at a time. The path then is compared against index paths
// to determine any changes. Read load_tree_files() and  status::Status::head_entries().
fn extend_path(prefix: &[u8], name: &[u8]) -> Vec<u8> {
    // root has no prefix
    if prefix.is_empty() {
        return name.to_vec();
    }

    let mut path = Vec::with_capacity(prefix.len() + 1 + name.len());
    path.extend_from_slice(prefix);
    // TODO: currently the path will be tested against index path which are of fixed format using
    // TODO: using '/'. We could use the os separator and do the conversion to an index path in the
    // TODO: caller. path.push(MAIN_SEPARATOR as u8);
    path.push(b'/');
    path.extend_from_slice(name);

    path
}

