use crate::cmd::error::DbError;
use crate::cmd::object::Object;
use rand::RngExt;
use rand::distr::Alphanumeric;
use sha1::{Digest, Sha1};
use std::io::ErrorKind;
use std::path::PathBuf;
use std::{fs, io};

pub(super) struct Database {
    pub(super) path: PathBuf
}

// toDo: info and packs files
impl Database {
    pub(super) fn store(&self, object: Object) -> Result<[u8; 20], DbError> {
        let obj_type = object.obj_type();
        let content = object.serialize();
        // The header for each object is: object type, a space, the length of the object(result of
        // serialization) and a nul byte. These are the bytes that will be used for compression
        let mut bytes = Vec::new();
        bytes.extend_from_slice(obj_type);
        bytes.push(b' ');
        bytes.extend_from_slice(content.len().to_string().as_bytes());
        bytes.push(0);
        // The final representation is header + content
        bytes.extend(content);
        let hash: [u8; 20] = Sha1::digest(&bytes).into();
        // the hash is bytes generated by Sha1
        // we need to map those bytes to their hex representation, decimal -> hex
        // don't confused it with utf-8
        // map [144, 58, 113, 173, 48, 13, 90, 161, 186, 12, ...] to [90, 3a, 71, ad, 30, 0d, 5a...].
        // Any u8 can be represented with at most 2 hex digits so the output is a String of length 40.
        // u8 spans from 0 to 255 which is equivalent to 0x00 - 0xFF
        // both the 20 raw bytes and the 40-character hex string are the same hash. They are two
        // representations of the same 160-bit value
        let hex: String = hash.iter().map(|b| format!("{:02x}", b)).collect();
        // the first 2 characters are the name of the folder in /objects, the rest are the name
        // of the file .lit/objects/90/3a71ad300d...
        // the two character split is just to avoid having of thousands of files in one directory,
        // which would slow down file systems
        let parent = self.path.join(&hex[..2]);
        // if the parent dir does not exist, create parent first .lit/objects/90/ before trying to
        // write tmp
        match fs::create_dir(&parent) {
            Ok(_) => {}
            Err(err) if err.kind() == ErrorKind::AlreadyExists => {
                if !parent.is_dir() {
                    return Err(DbError {
                        path: parent,
                        source: io::Error::new(
                            ErrorKind::AlreadyExists,
                            "object directory path exists but is not a directory",
                        ),
                    });
                }
            }
            Err(err) => {
                return Err(DbError {
                    path: parent,
                    source: err,
                });
            }
        }

        // If the hash already exists in .lit/objects/, the content is guaranteed to be identical
        // (same content -> same hash), so writing it again is pointless.
        let path = parent.join(&hex[2..]);
        if path.exists() {
            return Ok(hash);
        }
        let tmp_path = parent.join(gen_tmp_name());
        // this will create only the temp file and not any of the parent dir if missing
        // .lit/objects/90/tmp_obj_gNLJvt
        let compressed = deflate::deflate_bytes(&bytes);
        fs::write(&tmp_path, compressed).map_err(|err| DbError {
            path: parent.to_path_buf(),
            source: err,
        })?;

        // we return the rename error even if remove_file() fails because that was the main reason
        if let Err(err) = fs::rename(&tmp_path, &path) {
            // Try to clean up the temp file before returning the error
            let _ = fs::remove_file(&tmp_path);
            return Err(DbError {
                path: tmp_path,
                source: err,
            });
        }
        Ok(hash)
    }
}

pub(super) fn hash(obj_type: &[u8], content: &[u8]) -> [u8; 20] {
    // The header for each object is: object type, a space, the length of the object(result of
    // serialization) and a nul byte
    let mut bytes = Vec::new();
    bytes.extend_from_slice(obj_type);
    bytes.push(b' ');
    bytes.extend_from_slice(content.len().to_string().as_bytes());
    bytes.push(0);
    // The final representation is header + content
    bytes.extend(content);
    Sha1::digest(bytes).into()
}

// there is an edge case of a collision where 2 different processes could in theory generate the same
// tmp file name, and they will overwrite each others content, we have a case of competing writes, rare
// but can happen, could use Lockfile, but it is highly unlikely
fn gen_tmp_name() -> String {
    let suffix: String = (0..6)
        .map(|_| rand::rng().sample(Alphanumeric) as char)
        .collect();
    format!("tmp_obj_{suffix}")
}
