use crate::cmd::error::DbError;
use crate::cmd::object::Object;
use rand::RngExt;
use rand::distr::Alphanumeric;
use sha1::{Digest, Sha1};
use std::io::ErrorKind;
use std::path::Path;
use std::{fs, io};

pub(super) fn store(path: &Path, object: Object) -> Result<[u8; 20], DbError> {
    let obj_type = object.obj_type().as_bytes();
    let content = object.serialize();
    // The header for each object is: object type, a space, the length of the object(result of
    // serialization) and a null byte
    let mut bytes = Vec::new();
    bytes.extend_from_slice(obj_type);
    bytes.push(b' ');
    bytes.extend_from_slice(content.len().to_string().as_bytes());
    bytes.push(0);
    // The final representation is header + content
    bytes.extend(content);

    let hash: [u8; 20] = Sha1::digest(&bytes).into();
    // the hash is bytes generated by Sha1
    // we need to map those bytes to their hex representation, decimal -> hex
    // don't confused it with utf-8
    // map [144, 58, 113, 173, 48, 13, 90, 161, 186, 12, ...] to [90, 3a, 71, ad, 30, 0d, 5a...].
    // Any u8 can be represented with at most 2 hex digits so the output is a String of
    // length 40.
    // both the 20 raw bytes and the 40-character hex string are the same hash. They are two
    // representations of the same 160-bit value
    let hex: String = hash.iter().map(|b| format!("{:02x}", b)).collect();
    // the first 2 characters are the name of the folder in /objects, the rest are the name
    // of the file .lit/objects/90/3a71ad300d...
    // join() internally calls to_os_string() and returns owned data.
    let parent = path.join(&hex[..2]);
    // if the parent dir does not exist, create parent first .lit/objects/90/
    // create /90 first before trying to write tmp
    match fs::create_dir(&parent) {
        Ok(_) => {}
        Err(err) if err.kind() == ErrorKind::AlreadyExists => {
            if !parent.is_dir() {
                return Err(DbError {
                    path: parent,
                    source: io::Error::new(
                        ErrorKind::AlreadyExists,
                        "object directory path exists but is not a directory",
                    ),
                });
            }
        }
        Err(err) => {
            return Err(DbError {
                path: parent,
                source: err,
            });
        }
    }

    // If the hash already exists in .lit/objects/, the content is guaranteed to be identical
    // (same content -> same hash), so writing it again is pointless.
    let path = parent.join(&hex[2..]);
    if path.exists() {
        return Ok(hash);
    }
    // We use the tmp file pattern that protect us from what we could go wrong during writes.
    // If we started writing directly to 'path', .lit/objects/90/3a71ad300d..., and halfway
    // through the process our program crashes we would have a file that contains only half
    // the compressed data. Now the file exists, we assume, it's a valid object, we try to
    // read it, and get garbage. The object is corrupt, and the hash tells us it should be
    // there.
    // With the temp file approach the same crash happens, but the half-written data is at
    // tmp_obj_xYz. The final path never got created. We can retry the operation. The rename
    // process is atomic. Another process reading the directory at any point will either see
    // the old name or the new name, never neither, never both, never a half-renamed file.
    // The rename either happened or it didn't. It's all about atomicity, we want to make
    // sure that if the object exists it's always valid, or it's not there at all.
    let tmp_path = parent.join(gen_tmp_name());
    // this will create only the temp file and not any of the parent dir if missing
    // .lit/objects/90/tmp_obj_gNLJvt
    let compressed = deflate::deflate_bytes(&bytes);
    // Example:
    //     let tmp = PathBuf::from("/home/thanos/RustroverProjects/lit/hello.txt");
    //     let path = PathBuf::from("/home/thanos/RustroverProjects/lit/world.txt");
    //     fs::write(&tmp, "hello").unwrap();
    //     fs::rename(&tmp, &path).unwrap();
    //
    // The output is a single file world.txt containing "hello". Internally is just a pointer
    // update, no copying, no allocation. Very similar to move.
    // The filesystem allocates data blocks on disk, writes "hello" into them, and creates a
    // directory entry in /home/thanos/RustroverProjects/lit/ that says hello.txt -> data block 4827
    // (or whatever block number). When rename is called the filesystem does two things in
    // one atomic operation: it creates a new directory entry world.txt -> data block 4827
    // and removes the old entry hello.txt -> data block 4827. The data blocks on disk are
    // untouched. The bytes "hello" are sitting in the same physical location before and
    // after the rename. Only the directory's name-to-block mapping changed. At no point
    // does the data exist under both names
    fs::write(&tmp_path, compressed).map_err(|err| DbError {
        path: parent.to_path_buf(),
        source: err,
    })?;

    // we return the rename error even if remove_file() fails because that was the main reason
    if let Err(err) = fs::rename(&tmp_path, &path) {
        // Try to clean up the temp file before returning the error
        let _ = fs::remove_file(&tmp_path);
        return Err(DbError {
            path: tmp_path,
            source: err,
        });
    }
    Ok(hash)
}

// there is an edge case of a collision where 2 different processes could in theory generate the same
// tmp file name, and they will overwrite each others content, we have a case of competing writes, rare
// but can happen, could use Lockfile, but it is highly unlikely
fn gen_tmp_name() -> String {
    let suffix: String = (0..6)
        .map(|_| rand::rng().sample(Alphanumeric) as char)
        .collect();
    format!("tmp_obj_{suffix}")
}
