use crate::repo::object::Object;
use crate::repo::object::mode::Mode;
use crate::repo::object::oid::Oid;
use crate::repo::path::RepoPath;
use rand::RngExt;
use rand::distr::Alphanumeric;
use sha1::{Digest, Sha1};
use std::collections::HashMap;
use std::error::Error;
use std::path::PathBuf;
use std::{fmt, fs, io};

pub(crate) struct Database {
    pub(crate) path: PathBuf,
}

// TODO: info and packs files
impl Database {
    pub(crate) fn store(&self, object: Object) -> Result<Oid, DbError> {
        let obj_type = object.obj_type().to_string();
        let content = object.serialize();
        let bytes = encode(obj_type.as_bytes(), &content);
        let hash: [u8; 20] = Sha1::digest(&bytes).into();
        // the hash is bytes generated by Sha1
        // we need to map those bytes to their hex representation, decimal -> hex
        // don't confused it with utf-8
        // map [144, 58, 113, 173, 48, 13, 90, 161, 186, 12, ...] to [90, 3a, 71, ad, 30, 0d, 5a...].
        // Any u8 can be represented with at most 2 hex digits so the output is a String of length 40.
        // u8 spans from 0 to 255 which is equivalent to 0x00 - 0xFF
        // both the 20 raw bytes and the 40-character hex string are the same hash. They are two
        // representations of the same 160-bit value
        let oid = Oid::from_bytes(hash);
        // the first 2 characters are the name of the folder in /objects, the rest are the name
        // of the file .lit/objects/90/3a71ad300d...
        // the two character split is just to avoid having of thousands of files in one directory,
        // which would slow down file systems
        let hex = oid.to_hex();
        let parent = self.path.join(&hex[..2]);
        // if the parent dir does not exist, create parent first .lit/objects/90/ before trying to
        // write tmp
        match fs::create_dir(&parent) {
            Ok(_) => {}
            Err(err) if err.kind() == io::ErrorKind::AlreadyExists => {
                if !parent.is_dir() {
                    let err = io::Error::new(
                        io::ErrorKind::AlreadyExists,
                        "object directory path exists but is not a directory",
                    );
                    return Err(DbError::Io {
                        path: parent,
                        source: err,
                    });
                }
            }
            Err(err) => {
                return Err(DbError::Io {
                    path: parent,
                    source: err,
                });
            }
        }

        // If the hash already exists in .lit/objects/, the content is guaranteed to be identical
        // (same content -> same hash), so writing it again is pointless.
        // TODO: the above comment is not entirely true, we still need to Sha1 collision detection by
        // checking the object type, object size, the uncompressed content.
        // If any of those differ we need to return a collision error.
        // Read Notes for Sha1 collision attacks,
        // TODO: eventually on the rewrite move to 256
        let path = parent.join(&hex[2..]);
        // TODO: can this exists() call be a TOCTOU issue?
        if path.exists() {
            return Ok(oid);
        }
        let tmp_path = parent.join(gen_tmp_name());
        // this will create only the temp file and not any of the parent dir if missing
        // .lit/objects/90/tmp_obj_gNLJvt
        // TODO: we need to change this to zlib
        let compressed = deflate::deflate_bytes(&bytes);
        fs::write(&tmp_path, compressed).map_err(|err| DbError::Io {
            path: parent.to_path_buf(),
            source: err,
        })?;

        // we return the rename error even if remove_file() fails because that was the main reason
        if let Err(err) = fs::rename(&tmp_path, &path) {
            // Try to clean up the temp file before returning the error
            let _ = fs::remove_file(&tmp_path);
            return Err(DbError::Io {
                path: tmp_path,
                source: err,
            });
        }
        Ok(oid)
    }

    // even if someone edits the contents of a blob, we rehash before we try to parse, and it will
    // fail because the two hashes will not match
    // instead of changing the contents of the blob what they can do is create their own blob and then
    // make a tree point at it, this will also get caught because of the Merkle's tree nature. we
    // will hash the contents of the tree, and it will fail because the hash of the tree is generated
    // by the hash of its children.
    pub(crate) fn load(&self, oid: &Oid) -> Result<Option<Object>, DbError> {
        let hex = oid.to_hex();
        // always safe to index since hex is a valid 40 character long hex string
        let (parent, child) = hex.split_at(2);
        let path = self.path.join(parent).join(child);
        let content = match fs::read(&path) {
            Ok(content) => content,
            Err(err)
                if matches!(
                    err.kind(),
                    io::ErrorKind::NotFound | io::ErrorKind::IsADirectory
                ) =>
            {
                // TODO: should NotFound be an error or let the caller handle None?
                return Ok(None);
            }
            Err(err) => return Err(DbError::Io { path, source: err }),
        };

        let bytes = match inflate::inflate_bytes(&content) {
            Ok(bytes) => bytes,
            Err(err) => {
                return Err(DbError::Decompress {
                    oid: hex,
                    reason: err,
                });
            }
        };

        let hash: [u8; 20] = Sha1::digest(&bytes).into();
        if hash != oid.inner() {
            // tampered object: someone opened the file, changed its contents, compressed the new
            // content and wrote back to the file, the hashes do not match or someone changed the
            // object's path and set it to whatever was provided to load
            return Err(DbError::HashMismatch {
                path,
                expected: oid.inner(),
                actual: hash,
            });
        }
        // the information from any parsing error that occurs during loading an object is never returned
        // to the user. It means something is wrong with our on-disk format. Bad object with {oid}
        // is all they are going to see. The information is only needed for debugging.
        Ok(Some(
            Object::deserialize(&bytes).map_err(|_err| DbError::BadObject { oid: hex })?,
        ))
    }

    pub(super) fn load_tree_files(
        &self,
        oid: &Oid,
    ) -> Result<HashMap<RepoPath, (Oid, Mode)>, DbError> {
        let mut files = HashMap::new();
        self.collect_tree_files(&mut files, &RepoPath::new(), oid)?;

        Ok(files)
    }

    fn collect_tree_files(
        &self,
        files: &mut HashMap<RepoPath, (Oid, Mode)>,
        prefix: &RepoPath,
        oid: &Oid,
    ) -> Result<(), DbError> {
        let entries = match self.load(oid)? {
            Some(Object::Tree(entries)) => entries,
            Some(_) => {
                return Err(DbError::NotATree {
                    path: prefix.clone(),
                    oid: oid.to_hex(),
                });
            }
            None => {
                return Err(DbError::ObjectNotFound { oid: oid.to_hex() });
            }
        };

        for entry in entries {
            // if we walk src and has 1 file: main.rs then the path stored on the map is src/main.rs
            // it is the location of each file build incrementally one level at a time. The path then
            // is compared against index paths to determine any changes. Read load_tree_files() and
            // status::Status::head_entries().
            let path = prefix.join(&entry.name);
            if entry.mode.is_directory() {
                // dfs
                self.collect_tree_files(files, &path, &entry.oid)?;
            } else {
                files.insert(path, (entry.oid, entry.mode));
            }
        }
        Ok(())
    }

    // the way we resolve the shortest unique prefix for oids is by computing the parent dir, the first
    // 2 letters, and then the remaining one are the entry's name within parent. When we walk the dir
    // if there is an entry that starts with that prefix then it is a candidate. The dir can be polluted
    // by other non-lit related garbage which will be ignored.
    pub(crate) fn resolve_oid_prefix(&self, prefix: &str) -> Result<Oid, DbError> {
        if prefix.len() < 4 {
            return Err(DbError::Prefix(PrefixError::TooShort(prefix.to_string())));
        }
        
        if !prefix.bytes().all(|b| b.is_ascii_hexdigit()) {
            return Err(DbError::Prefix(PrefixError::BadHex(prefix.to_string())));
        }

        let (dir_name, file_prefix) = prefix.split_at(2);
        let path = self.path.join(dir_name);
        let entries = match fs::read_dir(&path) {
            Ok(read_dir) => read_dir,
            Err(err) if err.kind() == io::ErrorKind::NotFound => {
                return Err(DbError::Prefix(PrefixError::NotFound(prefix.to_string())));
            }
            Err(err) => return Err(DbError::Io { path, source: err }),
        };

        let mut matches = Vec::new();
        for entry in entries {
            let entry = match entry {
                Ok(entry) => entry,
                Err(err) => return Err(DbError::Io { path, source: err }),
            };
            let name = entry.file_name();
            let Some(name) = name.to_str() else { continue };
            if name.starts_with(file_prefix) {
                if name.len() != 38 {
                    continue;
                }
                // we avoid the heap allocation from: let hex = format!("{}{}", dir_name, name);
                let mut bytes = [0u8; 40];
                bytes[..2].copy_from_slice(dir_name.as_bytes());
                bytes[2..].copy_from_slice(name.as_bytes());
                if let Ok(oid) = Oid::from_hex_bytes(&bytes) {
                    matches.push(oid);
                }
            }
        }
        match matches.len() {
            0 => Err(DbError::ObjectNotFound {
                oid: prefix.to_string(),
            }),
            1 => Ok(matches[0]),
            _ => Err(DbError::Prefix(PrefixError::Ambiguous {
                prefix: prefix.to_string(),
                candidates: matches,
            })),
        }
    }
}

pub(crate) fn hash(obj_type: &[u8], content: &[u8]) -> Oid {
    Oid::from_bytes(Sha1::digest(encode(obj_type, content)).into())
}

// there is an edge case of a collision where 2 different processes could in theory generate the same
// tmp file name, and they will overwrite each others content, we have a case of competing writes, rare
// but can happen, could use Lockfile, but it is highly unlikely
// this is very similar to how tempfile generates the name
fn gen_tmp_name() -> String {
    let suffix: String = (0..6)
        .map(|_| rand::rng().sample(Alphanumeric) as char)
        .collect();
    format!("tmp_obj_{suffix}")
}

// header: <type> <len>\0<content>
fn encode(obj_type: &[u8], content: &[u8]) -> Vec<u8> { 
    // These are the bytes that will be used for compression
    let mut bytes = Vec::with_capacity(obj_type.len() + 12 + content.len());
    bytes.extend_from_slice(obj_type);
    bytes.push(b' ');
    bytes.extend_from_slice(content.len().to_string().as_bytes());
    bytes.push(0);
    // The final representation is header + content
    bytes.extend(content);
    bytes
}

#[derive(Debug)]
pub(crate) enum PrefixError {
    TooShort(String),
    Ambiguous {
        prefix: String,
        candidates: Vec<Oid>,
    },
    NotFound(String),
    BadHex(String),
}

#[derive(Debug)]
pub(crate) enum DbError {
    Io {
        path: PathBuf,
        source: io::Error,
    },
    Decompress {
        oid: String,
        reason: String,
    },
    HashMismatch {
        path: PathBuf,
        expected: [u8; 20],
        actual: [u8; 20],
    },
    BadObject {
        oid: String,
    },
    NotATree {
        path: RepoPath,
        oid: String,
    },
    ObjectNotFound {
        oid: String,
    },
    Prefix(PrefixError),
}

impl Error for DbError {}

impl fmt::Display for DbError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            DbError::Io { path, source } => write!(f, "{}: {source}", path.display()),
            DbError::Decompress { oid, reason } => {
                write!(f, "unable to unpack object {oid}: {reason}")
            }
            DbError::HashMismatch { path, .. } => {
                write!(f, "hash-path mismatch for '{}'", path.display())
            }
            DbError::BadObject { oid } => write!(f, "bad object {oid}"),
            DbError::NotATree { oid, .. } => write!(f, "not a tree object: {oid}"),
            DbError::ObjectNotFound { oid, .. } => write!(f, "object {oid} not found"),
            DbError::Prefix(err) => write!(f, "{}", err),
        }
    }
}

impl fmt::Display for PrefixError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            PrefixError::TooShort(prefix)
            | PrefixError::BadHex(prefix)
            | PrefixError::NotFound(prefix) => {
                write!(f, "Not a valid object name {}", prefix)
            }
            PrefixError::Ambiguous { prefix, candidates } => {
                writeln!(f, "short object ID {} is ambiguous", prefix)?;
                writeln!(f, "The candidates are:")?;
                for oid in candidates {
                    let hex = oid.to_hex();
                    writeln!(f, "{}", &hex[..7])?;
                }
                write!(f, "Not a valid object name {}", prefix)
            }
        }
    }
}
