use crate::repo::format::ObjectFormat;
use crate::repo::object::Object;
use crate::repo::object::mode::Mode;
use crate::repo::object::oid::Oid;
use crate::repo::os::{self, IoError, OsPath};
use crate::repo::repo_path::RepoPath;
use sha1::{Digest, Sha1};
use std::collections::HashMap;
use std::error::Error;
use std::{fmt, fs, io, result};

const MINIMUM_UNIQUE_PREFIX_LEN: usize = 4;

pub(crate) struct Database<'repo> {
    objects_dir: &'repo OsPath,
    object_format: ObjectFormat,
}

// TODO: info and packs files
impl<'repo> Database<'repo> {
    pub(super) fn new(objects_dir: &'repo OsPath, object_format: ObjectFormat) -> Self {
        Self {
            objects_dir,
            object_format,
        }
    }


    pub(crate) fn store(&self, object: Object) -> Result<Oid> {
        let obj_type = object.obj_type().to_string();
        let content = object.serialize();
        let bytes = encode(obj_type.as_bytes(), &content);
        let hash: [u8; 20] = Sha1::digest(&bytes).into();
        // the hash is bytes generated by Sha1
        // we need to map those bytes to their hex representation, decimal -> hex
        // don't confused it with utf-8
        // map [144, 58, 113, 173, 48, 13, 90, 161, 186, 12, ...] to [90, 3a, 71, ad, 30, 0d, 5a...].
        // Any u8 can be represented with at most 2 hex digits so the output is a String of length 40.
        // u8 spans from 0 to 255 which is equivalent to 0x00 - 0xFF
        // both the 20 raw bytes and the 40-character hex string are the same hash. They are two
        // representations of the same 160-bit value
        let oid = Oid::from_bytes(hash);
        // the first 2 characters are the name of the folder in /objects, the rest are the name
        // of the file .lit/objects/90/3a71ad300d...
        // the two character split is just to avoid having of thousands of files in one directory,
        // which would slow down file systems
        let hex = oid.to_hex();
        let parent = self.objects_dir.join_unchecked(&hex[..2]);
        // if the parent dir does not exist, create parent first .lit/objects/90/ before trying to
        // write tmp
        match fs::create_dir(&parent) {
            Ok(_) => {}
            Err(err) if err.kind() == io::ErrorKind::AlreadyExists => {}
            Err(err) => {
                return Err(DatabaseError::Io(IoError::new("mkdir", Some(&parent), err)));
            }
        }

        // If the hash already exists in .lit/objects/, the content is guaranteed to be identical
        // (same content -> same hash), so writing it again is pointless.
        // TODO: the above comment is not entirely true, we still need to Sha1 collision detection by
        // checking the object type, object size, the uncompressed content.
        // If any of those differ we need to return a collision error.
        // Read Notes for Sha1 collision attacks,
        // TODO: this does no guarantee anything it can be a directory with the same name
        //  if path.exists() {
        //     return Ok(oid);
        //  }
        //  need to detect corruption or hash collisions at this, we must call load() and handle the
        //  not_found error.
        let path = parent.join_unchecked(&hex[2..]);
        let compressed = deflate::deflate_bytes_zlib(&bytes);
        os::atomic_write(&parent, &compressed, &path)?;

        Ok(oid)
    }

    // even if someone edits the contents of a blob, we rehash before we try to parse, and it will
    // fail because the two hashes will not match
    // instead of changing the contents of the blob what they can do is create their own blob and then
    // make a tree point at it, this will also get caught because of the Merkle's tree nature. we
    // will hash the contents of the tree, and it will fail because the hash of the tree is generated
    // by the hash of its children.
    pub(crate) fn load(&self, oid: &Oid) -> Result<Object> {
        let hex = oid.to_hex();
        // always safe to index since hex is a valid 40 character long hex string
        let (parent, child) = hex.split_at(2);
        let path = self.objects_dir.join_unchecked(parent).join_unchecked(child);
        let content = match fs::read(&path) {
            Ok(content) => content,
            Err(err)
                if matches!(
                    err.kind(),
                    io::ErrorKind::NotFound | io::ErrorKind::IsADirectory
                ) =>
            {
                // we could also have a method find() -> Result<Option<Object>, DbError> and let the
                // caller decide the absence
                // initially I had load() return Result<Option<Object>, DbError> but most of the callers
                // would turn None into NotFound, adjust if it changes
                return Err(DatabaseError::ObjectNotFound { oid: hex });
            }
            Err(err) => return Err(DatabaseError::Io(IoError::new("read", Some(path), err))),
        };

        let bytes = match inflate::inflate_bytes_zlib(&content) {
            Ok(bytes) => bytes,
            Err(err) => {
                return Err(DatabaseError::Decompress {
                    oid: hex,
                    reason: err,
                });
            }
        };

        let hash: [u8; 20] = Sha1::digest(&bytes).into();
        if hash != oid.inner() {
            // tampered object: someone opened the file, changed its contents, compressed the new
            // content and wrote back to the file, the hashes do not match or someone changed the
            // object's path and set it to whatever was provided to load
            return Err(DatabaseError::HashMismatch {
                path,
                expected: oid.inner(),
                actual: hash,
            });
        }
        // the information from any parsing error that occurs during loading an object is never returned
        // to the user. It means something is wrong with our on-disk format. Bad object with {oid}
        // is all they are going to see. The information is only needed for debugging.
        Ok(Object::deserialize(&bytes).map_err(|_err| DatabaseError::BadObject { oid: hex })?)
    }

    pub(super) fn load_tree_files(&self, oid: &Oid) -> Result<HashMap<RepoPath, (Oid, Mode)>> {
        let mut files = HashMap::new();
        self.collect_tree_files(&mut files, &RepoPath::new(), oid)?;

        Ok(files)
    }

    fn collect_tree_files(
        &self,
        files: &mut HashMap<RepoPath, (Oid, Mode)>,
        prefix: &RepoPath,
        oid: &Oid,
    ) -> Result<()> {
        let Object::Tree(entries) = self.load(oid)? else {
            return Err(DatabaseError::NotATree {
                path: prefix.clone(),
                oid: oid.to_hex(),
            });
        };

        for entry in entries {
            // if we walk src and has 1 file: main.rs then the path stored on the map is src/main.rs
            // it is the location of each file build incrementally one level at a time. The path then
            // is compared against index paths to determine any changes. Read load_tree_files() and
            // status::Status::head_entries().
            // in object.rs::parse() there is a method called `parse_tree_entry()` which verifies the
            // entries name so join is safe. TODO: test it
            let path = prefix.join_bytes_unchecked(&entry.name);
            if entry.mode.is_directory() {
                // dfs
                self.collect_tree_files(files, &path, &entry.oid)?;
            } else {
                files.insert(path, (entry.oid, entry.mode));
            }
        }
        Ok(())
    }

    // the way we resolve the shortest unique prefix for oids is by computing the parent dir, the first
    // 2 letters, and then the remaining ones are the entry's name within parent. When we walk the dir
    // if there is an entry that starts with that prefix then it is a candidate. The dir can be polluted
    // by other non-lit related garbage which will be ignored.
    pub(crate) fn resolve_oid_prefix(&self, prefix: &str) -> Result<Oid> {
        if prefix.len() < MINIMUM_UNIQUE_PREFIX_LEN {
            return Err(PrefixError::TooShort(prefix.to_string()))?;
        }

        if !prefix.bytes().all(|b| b.is_ascii_hexdigit()) {
            return Err(PrefixError::BadHex(prefix.to_string()))?;
        }

        let (dir_name, file_prefix) = prefix.split_at(2);
        let path = self.objects_dir.join_unchecked(dir_name);
        let entries = match fs::read_dir(&path) {
            Ok(read_dir) => read_dir,
            Err(err) if err.kind() == io::ErrorKind::NotFound => {
                return Err(DatabaseError::Prefix(PrefixError::NotFound(prefix.to_string())));
            }
            Err(err) => return Err(DatabaseError::Io(IoError::new("opendir", Some(path), err))),
        };

        let mut matches = Vec::new();
        for entry in entries {
            let entry = match entry {
                Ok(entry) => entry,
                Err(err) => return Err(DatabaseError::Io(IoError::new("opendir", Some(path), err))),
            };
            let name = entry.file_name();
            let Some(name) = name.to_str() else { continue };
            if name.starts_with(file_prefix) {
                if name.len() != 38 {
                    continue;
                }
                // we avoid the heap allocation from: let hex = format!("{}{}", dir_name, name);
                let mut bytes = [0u8; 40];
                bytes[..2].copy_from_slice(dir_name.as_bytes());
                bytes[2..].copy_from_slice(name.as_bytes());
                if let Ok(oid) = Oid::from_hex_bytes(&bytes) {
                    matches.push(oid);
                }
            }
        }
        match matches.len() {
            0 => Err(DatabaseError::ObjectNotFound {
                oid: prefix.to_string(),
            }),
            1 => Ok(matches[0]),
            _ => Err(PrefixError::Ambiguous {
                prefix: prefix.to_string(),
                candidates: matches,
            })?,
        }
    }
}

pub(crate) fn hash(obj_type: &[u8], content: &[u8]) -> Oid {
    Oid::from_bytes(Sha1::digest(encode(obj_type, content)).into())
}

// header: <type> <len>\0<content>
fn encode(obj_type: &[u8], content: &[u8]) -> Vec<u8> {
    // These are the bytes that will be used for compression
    let mut bytes = Vec::with_capacity(obj_type.len() + 12 + content.len());
    bytes.extend_from_slice(obj_type);
    bytes.push(b' ');
    bytes.extend_from_slice(content.len().to_string().as_bytes());
    bytes.push(0);
    // The final representation is header + content
    bytes.extend(content);
    bytes
}

#[derive(Debug)]
pub(crate) enum PrefixError {
    TooShort(String),
    Ambiguous {
        prefix: String,
        candidates: Vec<Oid>,
    },
    NotFound(String),
    BadHex(String),
}

impl Error for PrefixError {}

impl fmt::Display for PrefixError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            // Git does not provide any more info
            PrefixError::TooShort(prefix)
            | PrefixError::BadHex(prefix)
            | PrefixError::NotFound(prefix) => {
                write!(f, "not a valid object name {}", prefix)
            }
            PrefixError::Ambiguous { prefix, candidates } => {
                writeln!(f, "short object ID {} is ambiguous", prefix)?;
                writeln!(f, "the candidates are:")?;
                for oid in candidates {
                    let hex = oid.to_hex();
                    // TODO: could this 7 character abbreviation produce identical representations
                    //  for different candidates?
                    writeln!(f, "{}", &hex[..7])?;
                }
                write!(f, "not a valid object name {}", prefix)
            }
        }
    }
}

type Result<T> = result::Result<T, DatabaseError>;

#[derive(Debug)]
pub(crate) enum DatabaseError {
    Io(IoError),
    Decompress {
        oid: String,
        reason: String,
    },
    HashMismatch {
        path: OsPath,
        expected: [u8; 20],
        actual: [u8; 20],
    },
    BadObject {
        oid: String,
    },
    NotATree {
        path: RepoPath,
        oid: String,
    },
    ObjectNotFound {
        oid: String,
    },
    Prefix(PrefixError),
}

impl DatabaseError {
    pub(super) fn is_object_not_found(&self) -> bool {
        matches!(self, Self::ObjectNotFound { .. })
    }
}

impl Error for DatabaseError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Io(source) => Some(source),
            Self::Decompress { .. } => None,
            Self::HashMismatch { .. } => None,
            Self::BadObject { .. } => None,
            Self::NotATree { .. } => None,
            Self::ObjectNotFound { .. } => None,
            Self::Prefix(source) => Some(source),
        }
    }
}

impl fmt::Display for DatabaseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            DatabaseError::Io(_) => write!(f, "object database I/O failed",),
            DatabaseError::Decompress { oid, .. } => {
                write!(f, "unable to unpack object {oid}")
            }
            DatabaseError::HashMismatch { path, .. } => {
                write!(
                    f,
                    "object contents do not match the hash in its path'{}'",
                    path.display()
                )
            }
            DatabaseError::BadObject { oid } => write!(f, "bad object {oid}"),
            DatabaseError::NotATree { oid, .. } => write!(f, "not a tree object: {oid}"),
            DatabaseError::ObjectNotFound { oid, .. } => write!(f, "object {oid} not found"),
            DatabaseError::Prefix(_) => write!(f, "could not resolve object id prefix"),
        }
    }
}

impl From<IoError> for DatabaseError {
    fn from(err: IoError) -> Self {
        Self::Io(err)
    }
}

impl From<PrefixError> for DatabaseError {
    fn from(err: PrefixError) -> Self {
        Self::Prefix(err)
    }
}
